### ISSUE TITLE
Accomodate sub-population RRH preferences in CAS matches (using data from ETO assessments and non-HMIS clients). 

### ISSUE THREAD

**Issue by iankozak** [open-path/Boston#14]
Youth, for example, should have options like:

- Interested in Youth RRH
 - Interested in non-Youth RRH (excluding Youth RRH)
 - Interested in all RRH (Youth and non-Youth)

For this Youth example, we'll also need to capture "Is Youth" flag for de-identified, non-HMIS records.

**Comment by iankozak** [comment]
Possible solution:

Set available client attributes to something like: interested in (general) RRH; interested in Youth RRH; interested in Vet RRH; interested in DV RRH.

Set those attributes based on TouchPoint assessment.

Update non-HMIS forms to include those additional RRH attributes.

Update CAS match rule options: "Must be interested in (general) RRH"; "Must be interested in Youth RRH"; "Must be interested in Vet RRH"; etc. This assumes a program is _either_ general RRH or a population-specific RRH.

Update CAS match rule for youth matching: 18-25 years old OR has "Is Youth" checkbox from non-HMIS form.

Estimate effort for the above: 1 day/6 hours

**Comment by margocramer** [comment]
Moved this to "scheduled for development" but actually getting it scheduled might be a question for Wed 6/19.

**Comment by iankozak** [comment]
Pending _Pathways_ Assessment for HMIS clients

**Comment by margocramer** [comment]
incorporated into #51
