### ISSUE TITLE
Conditional data quality report view by project type

### ISSUE THREAD

**Issue by lmckone** [open-path/Boston#20]
** 8/19 UPDATE: apply this logic to inventory information date and housing type in the project descriptors as well **

Not every section of the data quality report is pertinent to every project type. Spec for what to hide:

Street Outreach (4), Services Only (including RRH pre-placement) (6), Day shelter (11), Homelessness Prevention (12):
- Hide bed inventory in the project descriptors
- Hide unit inventory in the project descriptors
- Hide bed utilization 
- Hide unit utilization
- Hide bed and unit utilization summaries in the summary section

**Comment by margocramer** [comment]
sent to Laila for approval to move to product backlog. once there, will require effort estimate from GR.

**Comment by lmckone** [comment]
Re-opening this with a followup request - for the project types listed above, could we also hide "Information Date" in the project descriptors since it's attached to the inventory?
