### ISSUE TITLE
Reports for HIPPA compliance/monitoring

### ISSUE THREAD

**Issue by margocramer** [open-path/Boston#27]
REquirement of BAA with MassHealth (reasonable monitoring of system)- need reports for auditing purposes. One to show anomalies is user behavior, other to show user activity. BHCHP has something similar on their side that we should be able to copy or develop from. Start with making dropdown for agency.

**Comment by iankozak** [comment]
GR's notes from team call (from duplicate closed issue #12): Need to ensure users are removed from the system when the user no longer needs access. Beginning part of the process could be to provide each Agency with a report list of users, role/permissions, last activity date and potentially some metrics around what activities the user has performed during a set period of time (e.g. in last quarter).

Currently the "Agency" field attached to a user's profile is a free-form text field instead of a dropdown.

**Comment by margocramer** [comment]
sent to Laila for approval to move to product backlog. once there, will then need effort estimate from GR.

**Comment by iankozak** [comment]
Specific tasks (from team call 6/26):

- Make 'Agency' a drop-down in user profiles.

- Create admin section CRUD for managing Agency options.

- Create temporary/ad hoc report that lists all users, their current agency string, and a drop-down selection to allow DND to assign many users' their agencies quickly.

- Create new report with permissions such that 'Agency Site Admin' can see the recent activity of their agency's staff: last login, # unique client records accessed each month for the last 3 months.

- Create new admin report that shows all enabled user accounts and their last login date; sort by last login date ascending, and highlight those that have been more than 30 days.

**Comment by margocramer** [comment]
@iankozak can you clarify how many hours "3 days" is? thanks!

**Comment by iankozak** [comment]
@margocramer ~18:

1 day = 6 hours
1 week = 5 days

The idea with the estimate labels is to hopefully give sound, relative effort indications without unrealistic precision (and acknowledge it's harder to precisely estimate hours on very large or very small tasks). So we set the labels to be:

3 Hours 
1 Day
2 Days
3 Days
4 Days
1 Week
2 Weeks

BTW, once we start in on this particular feature, we'll probably break it into (at least) 3 separate stories/cards (each falling in the 3 hours-1 day range):

1). Make 'Agency' in user profiles be a dropdown; create an admin tool for managing those dropdown options; create a temporary admin page for an administrator to assign existing users agencies quickly.

2). Make a report for agency admins to see the activity of users at their agencies.

3). Make an admin report highlighting potentially inactive accounts.
