### ISSUE TITLE
parking and maintaining existing matches

### ISSUE THREAD

**Issue by margocramer** [open-path/Boston#36]
resolve issue created when someone with a PSH match is also matched with RRH. Issue has happened twice, likely to happen more frequently with Coordinated Entry & RRH assessments of clients on Chronic list. 

Discussed solutions:
1) PARK FOR FUTURE MATCHES BUT MAINTAIN PAST MATCHES
2) Create ability to park for specific routes (potentially more dev effort)

**Comment by iankozak** [comment]
A few thoughts:

When a client is parked **from a match**, the text there says "_Parking a client will remove them from this match and any proposed matches. The client will not be re-matched until the date specified has passed._" This would imply that other matches in progress should NOT be canceled, no? (And if other active matches are getting canceled now, I would call that a bug. We'll investigate....)

When a client is parked **from the client page**, the text says "REMOVE ALL OF THIS CLIENT’S ACTIVE MATCHES AND PREVENT FROM MATCHING" - which seems clear.

**Comment by margocramer** [comment]
@iankozak @eanders this is has been "appoved" - we're ready to hear from you about effort scoring!

**Comment by eanders** [comment]
Since the functionality didn't match up with the on-page description, we treated this as a bug and are in the process of fixing it. Should be finished up tomorrow.  Effort is roughly 2 hours.
