### ISSUE TITLE
Implement user access roles for population dashboards

### ISSUE THREAD

**Issue by lmckone** [open-path/Boston#37]
Mimic RRH dashboard user access structure for population dashboards. 

A given user should be able to see:
- Aggregate system-level data
- Their own agency's data with client-level drill downs

**Comment by lmckone** [comment]
- Group ok’d

- Who will be given access?

- HMIS WG

- Anyone can access - Ian will bring it to vets / leadership, but should come through the HMIS Admin

- When shared with HMIS WG, we should document the proper protocol for requesting access from the agency site admin, etc.

**Comment by eanders** [comment]
@lmckone The permission you'll need to grant are threefold.

1. A user must have a role that includes the "Can view censuses" permission
2. Any Data Access Assignments will be available for filtering and then drill-down
3. Finally, if you want a user to be able to see the reports that make up the details, you'll need to assign those particular reports as well.

**Comment by lmckone** [comment]
User must also have a role that includes "Can view assigned reports" permission
