### ISSUE TITLE
updating old pathways assessment scores for Pathways launch

### ISSUE THREAD

**Issue by margocramer** [open-path/Boston#40]
all assessments prior to 3/2/20 receive 48 points.

**Comment by eanders** [comment]
Update all assessments done in CAS prior to 3/2 with a new score of 48.

**Comment by margocramer** [comment]
@eanders I got the OK for this to be implemented.

**Comment by eanders** [comment]
@margocramer all non-HMIS clients with assessments prior to 3/2/2020 have been given an assessment score of 48 in CAS production.
