### ISSUE TITLE
Add step in CAS for HSA to accept client.

### ISSUE THREAD

**Issue by IanGendreau** [open-path/Boston#46]
Add a step between 4 and 5 in CAS. This will allow HSAs to accept a client into a program and cancel all other clients on a multiple match. Current set up will lock clients into multiple match until one client is housed. Some programs (MRVP for example) take a long time between acceptance and housing and clients who will not be receiving housing opportunity will still be locked into match.

**Comment by kimbotz** [comment]
Replacing with Github Issue #49
