### ISSUE TITLE
Triage touchpoint export

### ISSUE THREAD

**Issue by lmckone** [open-path/Boston#59]
Re-design the Touchpoint Export tool so that more data can be exported at a time

**Comment by lmckone** [comment]
@eanders I checked this out by exporting the touchpoint for june 2016 - now. The report ran relatively quickly (9 minutes), but when I hit "download" I got a 504 timeout, tried refreshing the page but kept getting the error so was unable to download the touchpoint. Also, the summary said the report was ~10,000, which is still less than the number of 'dismissals' I am getting from BPHC and Pine Street (I'm getting ~12,000 dismissals, and not everyone who was assessed has been dismissed), which makes me think there are still some assessments not coming through. When I can download the touchpoint I will pull some more examples. Thanks!

**Comment by eanders** [comment]
@lmckone we haven't gone back to 2016 for pulling TouchPoints.  Any chance you could start with a 2 year pull?  Any way you slice it, generating 12,000 really wide rows in Excel is going to be pretty slow, so you may not be able to download it all at once.

**Comment by lmckone** [comment]
@eanders I tried it in two 2-year batches and was able to download!

To clarify, when you say you haven't gone back to 2016 for pulling Touchpoints - I do see 2016 touchpoints for the Triage assessment coming through. Am I misunderstanding something?

**Comment by eanders** [comment]
@lmckone, we may have some old touch points, but they would have been fetched from ETO months ago.  That's probably fine, but in our recent effort to re-collect the Triage TouchPoints, we've only been going back to 1/1/2017.

**Comment by lmckone** [comment]
@eanders Gotcha. Are you planning to recollect the 2016 touchpoints at some point?

**Comment by eanders** [comment]
It wasn't on our radar, but we can.  Seeing as how we'll be moving away from those in less than 2 months, though, I'm not inclined to spend too much effort trying to collect them into the warehouse.

**Comment by lmckone** [comment]
@eanders That makes sense. We are using the assessments to track the number of people assessed to date (for budget, program design, etc.), so if there's a chance we are missing some from 2016, it would be great to have them in the warehouse. Even though the data structure of the assessment is changing soon, the old assessments aren't going away, and it's important to have an accurate record of the history of Triage. This isn't a priority with everything else going on at this point, but I do think there is value to making sure we all pulling in all historical assessments.
