### ISSUE TITLE
Interested in RRH but no release report update

### ISSUE THREAD

**Issue by lmckone** [open-path/Boston#66]
update language and name of report
take out interested in rrh and interested in youth rrh column
add ability to filter by location collected

**Comment by lmckone** [comment]
@allisonsinger add new title and description here

**Comment by allisonsinger** [comment]
Draft new title & description - open to edits & comments! https://docs.google.com/document/d/1Etl7x0DalHSZ9P1_2123KdmiqfRielgQaPRu6eR6r_0/edit?usp=sharing

**Comment by margocramer** [comment]
expand scope to include all clients who answered interested in SSVF, RRH and/or Homeless Set Asides

**Comment by iankozak** [comment]
/warehouse_reports/cas/rrh_desired

**Comment by lmckone** [comment]
Closed
