### ISSUE TITLE
viewing vacancies beyond the list displayed first

### ISSUE THREAD

**Issue by margocramer** [open-path/Boston#71]
I can visit cas.boston.gov/opportunities and view a list of of current vacancies, but if I try to view the more pages (in particular the 3rd and 4th, https://cas.boston.gov/opportunities?page=3 and https://cas.boston.gov/opportunities?page=4) I get an error page ("We're sorry, but something went wrong. If you are the application owner check the logs for more information.")

**Comment by eanders** [comment]
@margocramer a fix for this has been deployed.
