### ISSUE TITLE
no Pathways from BPHC or Bridge

### ISSUE THREAD

**Issue by margocramer** [open-path/Boston#73]
Per my conversation with @iankozak @cujocon1978 last Friday, Pathways from Bridge and BPHC are not making it into the Warehouse. 

@iankozak confirmed via call that this something GR can solve, but needs to be resolved somewhere by Social Solutions, DND or the agencies themselves. However, latest feedback from HMIS team is

 "Green River are the ones that are pulling down the touchpoints from the APIs so check in with them.  I know that Elliot and Josh at Social Solutions were working on some API issues but Pathways wasn't one of them" 

Can GR please confirm/restate what the issue is so we can troubleshoot as needed?

@jflynn-dnd @lmckone

**Comment by lmckone** [comment]
From our call with GR this morning: 

GR does not have admin rights on BPHC’s site. Either Jason or Social Solutions needs to give GR access to the Pathways touchpoint. Jen will email Josh and Jason requesting that they do this

**Comment by margocramer** [comment]
Thanks, all! Can Jen send the same email to Gina/Bridge and Josh?



[image: COB_B_Blue_square-01.png]

Margo Cramer

Advisor for Strategic Initiatives and Partnerships to End Homelessness

City of Boston Dept. of Neighborhood Development, Supportive Housing
Division

marguerite.cramer@boston.gov <rick.wilson@boston.gov> | 617-635-4201

(pronouns she/her/hers)


question about Coordinated Entry? email pathways@boston.gov for the fastest
response.

**Comment by iankozak** [comment]
Using an updated connection key, GR can now pull down assessments from BPHC successfully.

Also the code for scoring Pathways Assessments in the warehouse appears to be working, though a couple of assessment examples we looked at had issues; see Elliot's email 3/11.

**Comment by margocramer** [comment]
@iankozak we are seeing BPHC's assessments. 

I am unclear from the BPHC setup process about how involved GR needs to be in order for us to get Bridge's API set up and flowing into the warehouse. Can you confirm and clarify whether Social Solutions needs to be coordinating with you for setup, and if not, what information you need once the API is created in order to call Pathways touchpoints successfully?

**Comment by iankozak** [comment]
There's no client data at all from Bridge in the warehouse. IIRC, after Bridge moved to their own Enterprise installation of ETO, I believe they agreed they would try to get Social Solutions to configure nightly dumps (HUD-spec HMIS CSV exports of client and enrollment records) onto S3 and grant us API access.

Maybe @jflynn-dnd knows where all that landed? 

I don't know who can push that forward. It's a conversation between DND (who needs the data), Bridge (who needs to work with Social Solutions), Social Solutions (who needs to get the exports configured and running), and then Green River (to actually pull the data when it's available).

**Comment by lmckone** [comment]
Regina is currently working with Social Solutions to get the API set up. I'm not sure whether the holdup is on Bridge's end or Social Solutions end right now, but there is nothing DND or SS can do at this point to move things along. 


Once the API is set up, Regina will need to work with GR to get them an account (working w/ SS to make sure they have the right permissions to pull the assessment through the API)

**Comment by iankozak** [comment]
Cool. And do you know about getting actual HMIS data? (We need client records before we can pull TouchPoints associated with them.)

**Comment by lmckone** [comment]
@jflynn-dnd @kadraadderly do you know where Bridge is at with sending data to the warehouse?

**Comment by kadraadderly** [comment]
Bridge agreed to only send data for the CoC funded programs. Regina said
that she will get back to us about the RHY data. I do not know if anyone
was followed up after that.

[image: COB_B_Blue_square-01.png]

Kadra Adderly (pronouns: she/her/hers)

HMIS Coordinator & Youth Specialist | Supportive Housing Division

Department of Neighborhood Development

617.635.0267 (w)


Have data migration questions?

Visit here
<https://drive.google.com/drive/folders/1ev8-q4voeMql8oxebnJf4NYadP7Lw-K2?usp=sharing>
or
email HMISmigration@boston.gov


Need data or technical support?

Submit a case to the HMIS Help Desk
<https://www.boston.gov/departments/neighborhood-development/hmis-and-data-help-desk>
