### ISSUE TITLE
restricting "HSA" role to assigned programs

### ISSUE THREAD

**Issue by margocramer** [open-path/Boston#76]
As more staff are taking on the "HSA" role in CAS, can we consider adding permissions to these users so they can only edit their own programs? This might be embedded in an existing issue (ie @lmckone's work). Let's make sure it is called out explicitly and then close if so :)

**Comment by margocramer** [comment]
(as an aside, I can no longer edit the issue's associated "labels")

**Comment by iankozak** [comment]
So this capability has been in CAS for awhile (it came along with the original Set-Asides work), but not configured. My understanding is because HSAs have traditionally had broad access to see programs in the system, @IanGendreau (and/or others?) have been hesitant to bluntly enable restrictions.

**Comment by IanGendreau** [comment]
@margocramer You're right, this is tied to @lmckone 's work. We want to get all of this set so we can lock down CAS roles better. This has been on the table for a while and Lubov's work has finally started to push it forward.
