### ISSUE TITLE
some clients on "Coordinated Entry Assessment Report" are enrolled in housing programs

### ISSUE THREAD

**Issue by margocramer** [open-path/Boston#77]
can we omit these clients from the report? are there other examples that we can think of where clients should be omitted?

**Comment by iankozak** [comment]
Report should exclude clients with open housing programs with a move-in date.

Per call discussion 3/11/2020

**Comment by iankozak** [comment]
This logic should now be in place (on production). We'll add text to the top of the report noting that such clients are being excluded from the report anon.
