### ISSUE TITLE
timing out in CE Assessment report

### ISSUE THREAD

**Issue by margocramer** [open-path/Boston#78]
The report is unexpectedly timing out for some users. In one examples, it does not work as expected when the # of rows is low, and does work as expected when # of rows is high.

From Andrea Farina @ SFH:

> I selected SFH general services and it timed out  also tried SFH MAP (which should be a very small list) and SFH MATCH…each one timed out with the error saying  “504 Gateway Time out”
> 
> I also tested and was able to download the excel sheet from the overall list of 2229

**Comment by iankozak** [comment]
So the report should be much faster as of this morning - we haven't been able to make it timeout in production regardless of user or program selected.

Also the UI now requires you to select a project, which sounds like a better fit for the use cases of this particular report.
