### ISSUE TITLE
updates to COVID tool

### ISSUE THREAD

**Issue by margocramer** [open-path/Boston#80]
Hi all - a few requests for the COVID tool:

- put medical restriction field at the top (easier to locate, esp if this will be the most frequently used)
- add a "test administered date" so provider can say when a client was tested 
- add a permission level that can ONLY see medical restriction flag

**Comment by eanders** [comment]
@margocramer is the "test administered date" different from the "test date" under the "Testing Results" section, or should we just rename that?

**Comment by margocramer** [comment]
Ah! Thanks. I was looking in the clinical screening section, I see what you mean. I think the 2nd bullet it's fine as-is. Thank you!

**Comment by eanders** [comment]
OK, now on staging (we still need to run a quick internal test before going to production):

1. Medical restriction field has been moved to the top of the page.
2. There are separate permissions to edit and view for medical restrictions, screening, and clinical items.  Hopefully when combined with the history option, this allows for enough granularity.  

Edit allows access to the form.
View controls access to the status pills and any existing entries.  
You can cross-cut view and only allow access to the status and most-recent entry by removing access to the history.

Do you need us to adjust any settings on staging?
https://hmis-staging.boston.gov/admin/roles

**Comment by margocramer** [comment]
the permission levels look great. Thank you!
