### ISSUE TITLE
COVID name discrepancy bug?

### ISSUE THREAD

**Issue by margocramer** [open-path/Boston#81]
In staging - 

When I visit "John Fukasakyu" the COVID portal refers to him as "Philip Aaron." 

Unable to replicate with  "Emily Marie Andersen"

**Comment by iankozak** [comment]
Yeah, what you're seeing is a side effect of how fake demographic records on staging get created and updated. Name records change periodically on staging (as part of the fake data refresh process), and the "warehouse" record can be laggy to update.

That's unrelated to any of the COVID stuff or what you'll see in production.
