### ISSUE TITLE
updates from 4.1 user webinar

### ISSUE THREAD

**Issue by margocramer** [open-path/Boston#82]
Here are the ones I remember (forgot to take notes, yikes, maybe y'all did a better job!)

- pick list for isolation/quarantine locations (hold until I get you all a list...)
- exposure?/date under medical restriction tab
-other??

**Comment by iankozak** [comment]
That's all I had. The only potential actionable update I heard was for "medical exposure" (date) to be recorded separately from "medical restriction" information.  (And it still sounded like the definition of "medical restriction" varies between shelters, and from BHCHP.)
