### ISSUE TITLE
COVID Test Result Report

### ISSUE THREAD

**Issue by lmckone** [open-path/Boston#85]
Hi Green River,

We'd like to build a simple report listing:

- Client Id
- Name
- Test Date
- Test Result
- Any notes attached to the test
- Last Seen Location

For all clients who appear in health_emergency_tests

There should be a date range filter on Test Date and a filter for Last Seen location

This report should be viewable only by those with the COVID Level 3 role. If there isn't an easy way to associate a report with a role I'm fine just going through and manually granting access to everyone with Level 3.

**Comment by eanders** [comment]
@lmckone , here's a first pass at the test result report. https://hmis.boston.gov/warehouse_reports/health_emergency/testing_results

**Comment by eanders** [comment]
In terms of permissions, I've created a group called COVID Level 3.  If you add that to anyone wit the COVID Level 3 role, then they'll get access to the report.

**Comment by lmckone** [comment]
Thank you! I tried selecting all and the report crashed (I got a "page cannot be reached" error from chrome). It would be helpful if the default was displaying all test results that have come in and then the report could be filtered from there

**Comment by lmckone** [comment]
(It worked and looks great when I selected only one project)

**Comment by eanders** [comment]
Will do.  (There's a max length for get requests, which gets in the way of that.)  We'll adjust to default to all instead of none.

**Comment by eanders** [comment]
@lmckone , a fix has been deployed.

**Comment by lmckone** [comment]
Awesome, it's working now! One little things, could the default value for the start date be March 1th (the date of the first test on file) so we're displaying all test results as a default

**Comment by lmckone** [comment]
March 18th*

**Comment by eanders** [comment]
Deploying that change now.
